# Generated by Django 4.2.6 on 2023-11-22 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizado_por_inventarios', to='personal.bombero', verbose_name='Realizado Por'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='revisado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisado_por_inventarios', to='personal.bombero', verbose_name='Revisado Por'),
        ),
    ]
